### ISSUE TITLE
5. GitHub Actions for project set-up and build is working using JAR, and Docker on GitHub Actions. - Jordan

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#10]

**Comment by stonejcartman96** [comment]
Difficulty: Medium

User Story: GitHub Actions for project set-up and build is working using JAR, and Docker on GitHub Actions

Task:

- Ensure that project set up is working using JAR 
- Ensure that build project set is working using Docker


Acceptance:

- Passes a test
- Members approve at the review stage
