### ISSUE TITLE
8. Code of Conduct defined. - Milda

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#11]
Difficulty: Easy

User Story: Require a code of conduct which respects all needs of the team. 

Task:
The team shall meet up to discuss the code of conduct required to work as a functioning team on teams.
 We shall assign a member to codify and write our agreement on GiTHub. Once verified we will write approved on the ticket

Acceptance: 
All members shall review the CoC in GitHub and approve the CoC via ticket

**Comment by alexpat1122** [comment]
Milda has created the code of conduct and it is now currently under review.

**Comment by RandomUni** [comment]
Additions to code of conduit have been made now, feel free to review at a time that is personally suitable

**Comment by SJ-Maguire** [comment]
looks good milda, happy for you to move this to done if everyone else is
