### ISSUE TITLE
3. Project builds to self-contained JAR with Maven. - Milda

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#5]

**Comment by RandomUni** [comment]
I pushed the change to develop branch, feel free to add changes to master if they work with GitHub Actions. Seems to work fine on my end. Also, unsure if we need just the jar file or the whole code, so feel free to remove things if wanted

**Comment by stonejcartman96** [comment]
Difficulty: Medium 

User Story: Project builds to self-contained JAR with Maven

Task:

- Create a Jar file within Maven
- Make it self contained 

Acceptance:

- Verified that
