### ISSUE TITLE
2. Product Backlog created. - Jordan

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#6]

**Comment by stonejcartman96** [comment]
Difficulty: Easy

User Story: We are require to set up a process of document all the mini process in our team. In agile development this is called a product back log 

Task:

- Create documentation and rules for the product backlog
- Create a labelling system for products in the backlog
- Ensure that all products have have been created for the current sprint. 
- Ensure all products follow the methods outline 


Acceptance:

- Members approve of documentation and processes.
