### ISSUE TITLE
4. Dockerfile for project set-up and works. - Sara

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#7]

**Comment by SJ-Maguire** [comment]
having issues with docker at the moment and waiting for my company's helpdesk to get back to me

**Comment by stonejcartman96** [comment]
Difficulty: Medium 

User Story: Push project out once all tasks are complete.

Task:

- Ensure all products have been completed
- Perform the task of pressing the butto

Acceptance:

- Members approval
