### ISSUE TITLE
7. First release created on GitHub. - Sara

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#8]

**Comment by stonejcartman96** [comment]
Difficulty: Medium

User Story: Push project out once all tasks are complete.

Task:

Ensure all products have been completed
Perform the task of pressing the button
Acceptance:

Members approval

**Comment by alexpat1122** [comment]
I have created a release and pushed it to the github master branch.

This has been reviewed by Milda.
