### ISSUE TITLE
6. Correct branches for GitFlow workflow created - includes master, develop, and release branches. - Aleksandrs

### ISSUE THREAD

**Issue by alexpat1122** [alexpat1122/SET08403-2022-3-GROUP-B#9]

**Comment by alexpat1122** [comment]
might want to push to the branches just to make sure they are working?

**Comment by stonejcartman96** [comment]
User Stories:  Different branches are required to allow for agile development and review of code from each member in the team

Tasks: Creation of a master branch
         Creation of a development branch
         Creation of a Release branch


Acceptance: Has been verified by the members of the team
